name: Deploy Project
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: install node js
        uses: actions/setup-node@v6
        with:     
          node-version: '18'
      - name: install dependencies
        run: npm ci
      - name: run lint
        run: npm run lint
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      -name: checkout code
        uses: actions/checkout@3
      - name: install node js
        uses: actions/setup-node@v6
        with:
          node-version: '18'
      - name: install dependencies
        run: npm ci      
      - name: run test
        run: npm test
      - name: test completed
        run: echo "Tests Completed Successfully"
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      -name: checkout code
        uses: actions/checkout@v3
      - name: install node js
        uses: actions/setup-node@v6
        with:
          node-version: '18'
      - namne: install dependencies
        run: npm ci
      - name: build project
        run: npm run build
      - name: build completed
        run: echo "Build Completed Successfully"


